services:
  - type: web
    name: crop-app
    runtime: python
    buildCommand: "pip install -r crop-backend/requirements.txt"
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
    plan: free
    rootDir: crop-backend